source 'https://rubygems.org'

gem 'spree', '~> 3.7.0'
gem 'spree_auth_devise', '~> 3.5'
gem 'spree_gateway', '~> 3.4'
gem 'rails-controller-testing'

gem 'smarter_csv'
gem 'sidekiq'
gem 'sidekiq-status'

group :test do
  require 'ffaker'
  gem 'factory_bot'
end

group :development do
  gem 'pry-byebug'
end

gemspec
